export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'


export const LOGOUT_USER = 'LOGOUT_USER'

export const UPLOAD_IMAGE="UPLOAD_IMAGE"

export const UPLOAD_IMAGE_REGISTER="UPLOAD_IMAGE_REGISTER"

export const HANDLE_CHANGE="HANDLE_CHANGE"

export const CLEAR_UPLOADS="CLEAR_UPLOADS"


export const CHANGE_PAGE="CHANGE_PAGE"

export const showSideBar="ShowSideBar"

export const CHANGE_COLOR="CHANGE_COLOR"


export const ALL_USERS="ALL_USERS"

export const DELETE_USER="DELETE_USER"

export const GET_CURRENT_USER="GET_CURRENT_USER"

export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR="UPDATE_USER_ERROR"

export const GET_ALL_MOVIES="GET_ALL_MOVIES"
export const GET_ALL_LIST="GET_ALL_LIST"

export const DELETE_MOVIE="DELETE_MOVIE"
export const DELETE_LIST="DELETE_LIST"

export const UPDATE_MOVIE="UPDATE_MOVIE"







